trigger:
  branches:
    include:
      - main
variables:
  - group: ecommerce-values

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
    displayName: 'Instalar Terraform'

  # Inicializar Terraform
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        terraform init
    displayName: 'Terraform Init'

  # Plan de Terraform
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        terraform plan
    displayName: 'Terraform Plan'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        terraform apply 
    displayName: 'teraform apply'
